# Basic
title: Andrew Kornberg
subtitle: abeunt studia in morse
welcome_message:
description: Hi, I'm Kornberg, a wild programmer & PhD. candidate
creator: <a href="http://twitter/andrew_kornberg">@andrew_kornberg</a>

url: "http://kornbergfresnel.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My open-source projects, url: 'http://kornbergfresnel.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: u/5104230793
    github: KornbergFresnel
    twitter: andrew_kornberg
    gplus: 107108267983477358170
    mail: kornbergfresnel@outlook.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
